name: Deploy CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Create folder for build
        run: mkdir -p out

      - name: Build website
        uses: shalzz/zola-deploy-action@v0.19.1
        env:
          BUILD_DIR: out
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts

      - name: List all files in the build directory
        run: ls -R out

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'out'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
